## Feature engineering configuration
# universe: may be a UUID (universe_id) or a universe_name string present in transformed.symbol_universes
# If you prefer to lock to a specific load, replace the universe value with the matching universe_id UUID.

universe: IPO_Before_2020_All_Fundamentals_GT500_OCHLV_500MM_to_1B_Net_Income

folder: IPO2020_500Mto1B_20250821T202532Z

collection_dates:
  start_date: '2020-01-01'
  end_date: '2025-07-31'

data_switches:
  fundamentals:
    balance_sheet: true
      offset: 45
    cash_flow: true
      offset: 45
    income_statement: true
      offset: 45
    earnings_call_transcripts: true
      offset: 45
    insider_transactions: true
      offset: 5
  fred:
    commodities: true
    economic_indicators: true
  ohlcv:
    time_series_daily_adjusted: true

# Validation notes:
# 1. Detect if "universe" matches UUID regex -> treat as universe_id; else treat as universe_name.
# 2. Validate existence in transformed.symbol_universes before running pipeline.
# 3. Future extension: allow per-switch date overrides or dependency inference.
